### ISSUE TITLE
Settings and History are not portable from one computer to another

### ISSUE THREAD

**Issue by KrisZane** [SwensenSoftware/im-only-resting#69]
So when I move from one PC to another, it seems I am not able to retain my history, would it be at all possible to make a portable "flag" of some kind to make the program work in it's own home directory?

Also might I add this software is a great idea. :P

**Comment by stephen-swensen** [comment]
Hi @KrisZane - thanks for the feedback and taking the time to make this request!

Unfortunately, changing the location of the settings and history is non-trivial because they rely on built-in .NET APIs: https://msdn.microsoft.com/en-us/library/aa730869(v=vs.80).aspx. Specifically, we use "user scoped" settings which partition settings on a per-user basis (generally a boon on a multi-user system). Therefore, given the LOE vs. benefit, it is unlikely this request will be implemented.

That being said, you may be able to manually copy your history and settings from one computer to another. The settings are stored in a location like `C:\Users\<user name>\AppData\Local\Swensen\<.net generated hash>\<app version number>\user.config`. Good luck!

**Comment by KrisZane** [comment]
Thanks for the heads up, I will look into that. :)
